### ISSUE TITLE
Unknown database 'user'

### ISSUE THREAD

**Issue by wsAndy** [xiaoxian521/pure-admin-backend#2]
After `pnpm install` and `pnpm start`.

=====================================================
[nodemon] starting `node -r ts-node/register src/server.ts`
info:    
    ################################################
    🛡️  Swagger文档地址: http://localhost:3000 🛡️
    ################################################
  
error:   Unknown database 'user'

**Comment by xiaoxian521** [comment]
数据库开启 具体看 https://www.bilibili.com/video/BV1kg411v7QT/

**Comment by jamesleekko** [comment]
> 数据库开启 具体看 https://www.bilibili.com/video/BV1kg411v7QT/

数据库开启了  还是报这个错  是要自己建库和建表吗
